### ISSUE TITLE
Use abstract-to-meta to make it easier to write abstracts

### ISSUE THREAD

**Issue by eliocamp** [rstudio/rticles#353]
Writting the batract section in the yaml is a bit cumbersome, it's not clear how to include inline R code, and RStudio auto indent feature doesn't recognise it properly. Recently I found out about the abstract-to-meta lua filter which allows the user to write the abstract as part of the body and then moves that to the metadata :

https://github.com/pandoc/lua-filters/tree/master/abstract-to-meta

It works like a charm. With it it's even possible to write the abstract as the last section of the document, which would make it even more natural to include results from the analysis. 

Would you consider transitioning templates into using this filter?

---

By filing an issue to this repo, I promise that

- [x] I have fully read the issue guide at https://yihui.name/issue/.
- [x] I have provided the necessary information about my issue.
    - If I'm asking a question, I have already asked it on Stack Overflow or RStudio Community, waited for at least 24 hours, and included a link to my question there.
    - If I'm filing a bug report, I have included a minimal, self-contained, and reproducible example, and have also included `xfun::session_info('rticles')`. I have upgraded all my packages to their latest versions (e.g., R, RStudio, and R packages), and also tried the development version: `remotes::install_github('rstudio/rticles')`.
    - If I have posted the same issue elsewhere, I have also mentioned it in this issue.
- [x] I have learned the Github Markdown syntax, and formatted my issue correctly.

I understand that my issue may be closed if I don't fulfill my promises.

**Comment by cderv** [comment]
Thanks ! 

This is related to discussion in https://github.com/rstudio/rmarkdown/issues/1963 about including more external lua filter in the tools. 

This is something that we could consider. The question is how best and where it should lived. 

Thank you for the suggestion ! We'll see the upvote on this feature request!
